import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Duc Loi",
  description: "Generated by create next app",
};

export default function RegisterationLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex items-center justify-center bg-[#f8f4f4]`}>
        {children}
      </body>
    </html>
  );
}